name: STAKE CI

on:
  push:
    branches:
      - main

jobs:

  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Backend
        run: |
          cd backend
          npm install

      - name: Test Backend
        run: |
          cd backend
          npm run test

      - name: Build Backend
        run: |
          cd backend
          npm run build

  frontend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Frontend
        run: |
          cd frontend
          npm install

      - name: Test Frontend
        run: |
          cd frontend
          npm run test

      - name: Build Frontend
        run: |
          cd frontend
          npm run build